### ISSUE TITLE
Formulaire produits

### ISSUE THREAD

**Issue by adelinefreyja** [devilishfreyja/webcraft#1]
Le champ "Promotion" du formulaire d'ajout de produit ne permet que l'insertion d'une chaîne de caractères.

**Comment by adelinefreyja** [comment]
Le champ Promotion prend maintenant en compte un integer, mais le formulaire ne s'envoie pas en BDD.

**Comment by ghost** [comment]
Corrigé, nécessite une réinstallation de la BDD.
